.github/workflows/go.yml, Makefile, README.md, go.sum
resolves part of https://github.com/font/gatekeeper-operator/issues/2
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> add github actions CI

.github/workflows/go.yml, Makefile
continue to address https://github.com/font/gatekeeper-operator/issues/2
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> add test action

.github/workflows/go.yml, api/v1alpha1/gatekeeper_types.go, config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml
resolves https://github.com/font/gatekeeper-operator/issues/6
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> crd validation

.github/workflows/image.yml
Signed-off-by: tchughesiv <tchughesiv@gmail.com>
=> remove versioned image tag

controllers/gatekeeper_controller.go
Added support for setting owned resources to resolve #18
=> Added support for setting owned resources

.github/workflows/go.yml, Makefile, test/gatekeeper_controller_test.go, test/suite_test.go
=> Add gatekeeper installation e2e test

Makefile, README.md, bundle.Dockerfile, bundle/manifests/gatekeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1beta1_clusterrole.yaml, bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml, bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml, bundle/metadata/annotations.yaml, bundle/tests/scorecard/config.yaml, config/manager/kustomization.yaml, config/manifests/bases/gatekeeper-operator.clusterserviceversion.yaml, config/manifests/kustomization.yaml, config/rbac/role.yaml, controllers/gatekeeper_controller.go
1. added bundle files
1. added make target for generating bundle and index image
1. added instructions in readme
1. also added missing permission for `gatekeepers/finalizers`
=> add OLM install integration

Makefile, config/samples/gatekeeper_with_all_values.yaml, controllers/gatekeeper_controller.go, controllers/gatekeeper_controller_test.go, test/gatekeeper_controller_test.go, test/util/util.go
Fix #45 
Signed-off-by: ruromero <rromerom@redhat.com>
=> Add cr overrides e2e tests

README.md, api/v1alpha1/gatekeeper_types.go, config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml, controllers/gatekeeper_controller.go, controllers/gatekeeper_controller_test.go, pkg/bindata/bindata.go, pkg/util/util.go, test/gatekeeper_controller_test.go
Fix #19 missing item for configuring `validatingWebhook`
Depends on #50
=> Validating webhook

.github/workflows/image.yml
This depends on #66.
Fixes #47
=> Add github action workflow steps to build and push OLM images

Makefile, bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml, config/gatekeeper/apps_v1_deployment_gatekeeper-audit.yaml, config/gatekeeper/apps_v1_deployment_gatekeeper-controller-manager.yaml, config/samples/gatekeeper_with_all_values.yaml, config/samples/operator_v1alpha1_gatekeeper.yaml, pkg/bindata/bindata.go
no changes identified except version
=> upgrade gatekeeper to v3.2.2

.github/workflows/go.yml, Makefile
=> Add workflow step to verify bundle

.github/workflows/go.yml, Makefile, test/bats/helpers.bash, test/bats/test.bats, test/bats/tests/bad/bad_cm.yaml, test/bats/tests/bad/bad_cm_audit.yaml, test/bats/tests/bad/bad_deployment.yaml, test/bats/tests/bad/ignore_label_ns.yaml, test/bats/tests/bad/no_dupe_cm_2.yaml, test/bats/tests/bad/opa_no_limits.yaml, test/bats/tests/constraints/all_cm_gatekeeper_label_unique.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper-dryrun.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper.yaml, test/bats/tests/constraints/all_cm_must_have_gatekeeper_audit.yaml, test/bats/tests/constraints/containers_must_be_limited.yaml, test/bats/tests/good/good_cm.yaml, test/bats/tests/good/no_dupe_cm.yaml, test/bats/tests/good/opa.yaml, test/bats/tests/good/playground_ns.yaml, test/bats/tests/sync.yaml, test/bats/tests/sync_with_exclusion.yaml, test/bats/tests/templates/k8scontainterlimits_template.yaml, test/bats/tests/templates/k8srequiredlabels_template.yaml, test/bats/tests/templates/k8suniquelabel_template.yaml
=> E2E testing

Makefile, bundle.Dockerfile, bundle/metadata/annotations.yaml
set both channel and default channel to `stable`
=> set default channel in bundle metadata

api/v1alpha1/gatekeeper_types.go, api/v1alpha1/zz_generated.deepcopy.go, bundle/manifests/gatekeeper-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml, bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml, config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml, controllers/gatekeeper_controller.go, controllers/gatekeeper_controller_test.go, test/util/util.go
E2E tests will follow.
Fixes #79 
/cc @fedepaol
=> Add NamespaceSelector to Gatekeeper Operator API

.github/workflows/olm.yml, Makefile, config/olm-install/install-resources.yaml, config/olm-install/kustomization.yaml
new PR using existing test, per suggestions by @font
=> OLM e2e test

.github/workflows/image.yml, .github/workflows/release.yml, Makefile, deploy/gatekeeper-operator.yaml
=> Add GitHub Actions workflow to automate releases

Makefile, README.md, main.go
=> Add env var to run operator outside cluster

.github/workflows/go.yml, .github/workflows/image.yml, .github/workflows/olm.yml, .github/workflows/release.yml, Dockerfile, Makefile, bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml, config/manager/kustomization.yaml, deploy/gatekeeper-operator.yaml, main.go, pkg/version/base.go, pkg/version/version.go
=> Add and log versioning info for operator

controllers/gatekeeper_controller.go, controllers/gatekeeper_controller_test.go, test/gatekeeper_controller_test.go
=> Add support for overriding failurePolicy and namespaceSelector in MutatingWebhookConfiguration

.github/workflows/go.yml, Makefile, config/samples/gatekeeper_e2e_test.yaml, test/bats/test.bats, test/bats/tests/mutations/k8sexternalip_assign.yaml, test/bats/tests/mutations/k8sownerlabel_assignmetadata.yaml, test/bats/tests/mutations/mutate_cm.yaml, test/bats/tests/mutations/mutate_svc.yaml
=> Add Gatekeeper bats e2e tests for mutation

Makefile, config/gatekeeper/apiextensions.k8s.io_v1beta1_customresourcedefinition_assign.mutations.gatekeeper.sh.yaml, config/gatekeeper/apiextensions.k8s.io_v1beta1_customresourcedefinition_assignmetadata.mutations.gatekeeper.sh.yaml, config/gatekeeper/apiextensions.k8s.io_v1beta1_customresourcedefinition_configs.config.gatekeeper.sh.yaml, config/gatekeeper/apiextensions.k8s.io_v1beta1_customresourcedefinition_constraintpodstatuses.status.gatekeeper.sh.yaml, config/gatekeeper/apiextensions.k8s.io_v1beta1_customresourcedefinition_constrainttemplatepodstatuses.status.gatekeeper.sh.yaml, config/gatekeeper/apiextensions.k8s.io_v1beta1_customresourcedefinition_constrainttemplates.templates.gatekeeper.sh.yaml
This version of `kustomize` matches the latest GitHub Actions virtual environment, which includes changes to the line wrapping of the description field of manifests.
=> Update version of kustomize

api/v1alpha1/gatekeeper_types.go, bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml, bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml, config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml, config/manager/manager.yaml, controllers/gatekeeper_controller.go
=> Deprecate Gatekeeper CR Image field and use env var instead

Makefile, PROJECT, bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml, config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml, config/crd/kustomizeconfig.yaml, config/crd/patches/cainjection_in_gatekeepers.yaml, config/crd/patches/webhook_in_gatekeepers.yaml, test/e2e/e2e.go, test/e2e/gatekeeper_controller.go
- Upgrade CRD to v1
- make manifests
- make bundle
- Update generated operator-sdk configs for CRD v1
- Update code to import and use CRD v1 package
Closes #159
=> Upgrade CRD to v1

bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml, config/manager/manager.yaml, controllers/gatekeeper_controller.go
=> Use RELATED_IMAGE_GATEKEEPER env var name for Gatekeeper image

Makefile, README.md
Also updates .gitignore to allow using vscode.
=> Option for using podman in Makefile

.github/workflows/release.yaml
Attempting to prevent this type of error https://github.com/gatekeeper/gatekeeper-operator/runs/3624669918?check_suite_focus=true.
=> Move Go setup step earlier in job

go.mod, go.sum, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
https://github.com/advisories/GHSA-cg3q-j54f-5p7p
=> chore: update github.com/prometheus/client_golang CVE-2022-21698

Dockerfile, Makefile
=> Enable CGO
