gatekeeper/gatekeeper-operator

Dockerfile

By using the local vendor folder instead of downloading the modules, we rely on the repo as being the source of truth for dependencies.

Use vendoring in dockerfile.

---

Makefile

This removes the one shell requirement to have all make recipe lines
passed to a single shell invocation. While this can improve performance
and is useful for sharing environment variables across recipe lines
without `;` and escaping the newline character, once it is set anywhere
in the Makefile, then all make recipe lines for each target will be
provided to a single invocation of the shell. This removal will avoid
any confusion and keep the Makefile contents as consistent as possible
to the originally generated Makefile from operator-sdk.

Remove ONESHELL requirement for all make recipes

---

Makefile

Makefile expects the target to be a file, this isn't applicable to most
targets in the Makefile. So let's mark them as such for good make
hygiene.
This also changes the `kustomize` and `controller-gen` targets to be more
make-like by making them depend on the binaries as targets.

Tag most Makefile targets as .PHONY

---

api/v1alpha1/gatekeeper_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml
controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go

This updates the integer primitive types of API spec fields to match the type expected by Gatekeeper and Kubernetes.

Update API spec fields' primitive types

---

controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go

Depends on https://github.com/font/gatekeeper-operator/pull/33
Partially addresses #19 
Adds CR overrides for all common spec fields:
* spec.image
* spec.affinity
* spec.nodeSelector
* spec.podAnnotations
* spec.tolerations
* spec.resources
* spec.webhook.failurePolicy
Also added the following container arguments overrides for:
* spec.audit.auditInterval
* spec.audit.constraintViolationLimit
* spec.audit.auditFromCache
* spec.audit.auditChunkSize
* spec.audit.logLevel
* spec.audit.emitAuditEvents
* spec.webhook.logLevel
* spec.webhook.emitAdmissionEvents

Apply CR overrides

---

.github/workflows/image.yml
api/v1alpha1/gatekeeper_types.go
bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml
config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml
config/manager/kustomization.yaml

This is future proofing the image name to make sure we don't have to rename it in the future that may cause confusion and inconsistencies if we already have a released version of the operator. The thinking is that if we ever need to publish the operator image to another registry repo e.g. `docker.io/openpolicyagent`, the `operator` image name can be ambiguous and confusing. This change makes it more clear by renaming the image to `gatekeeper-operator`.

Rename operator image to gatekeeper-operator

---

.github/workflows/go.yml
Makefile
README.md
controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go
test/gatekeeper_controller_test.go

Fix #51 
Sets the current namespace to any namespaced object and any object that has a reference to the namespace will be overridden during the reconciliation.
The objects having references to the namespace are the following:
* clusterrolebinding:subject
* rolebinding:subject
* controller-manager:exept-namespace container argument
* validatingWebhook:clientConfig
In case there were multiple namespaces running the gatekeeper operator, the cluster-scoped objects might need to be updated in order to add a new clientConfig to the validatingWebhookConfiguration and more subjects to the clusterRoleBinding.
Signed-off-by: ruromero <rromerom@redhat.com>

Allow gatekeeper to run in any namespace

---

controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go

remove annotations from audit and webhook files when installing on openshift, per https://github.com/open-policy-agent/gatekeeper#running-on-openshift-4x

fix operator installation on OpenShift

---

.github/workflows/image.yml

This adds some common global environment variables to simplify maintenance and fixes the OLM images being pushed to quay due to a lack of the go environment being set up.

Fix github action workflow steps to build and push OLM images

---

Makefile
bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml

fixes permissions issue on openshift without having to build a separate image. tested on my cluster and it works the same as the image I created using `make bundle KUBE_DISTRIBUTION=openshift`

use openshift csv in bundle by default

---

api/v1alpha1/gatekeeper_types.go
bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml
config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml
config/rbac/base/role.yaml
controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go
main.go
test/gatekeeper_controller_test.go

Fix #70 
Signed-off-by: ruromero <rromerom@redhat.com>
I think the included changes should cover the most common use cases.
The operator uses the WATCHED_NAMESPACE to decide where to deploy the namespaced objects like the Server Cert Secret but the Gatekeeper resource is now clustered.
As the operator currently only allows for Gatekeeper resources with name `gatekeeper` it should avoid conflicts.

Cluster scoped operator and custom resource

---

bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
config/rbac/base/role.yaml
controllers/gatekeeper_controller.go

This permission was missing and was causing issues when deploying the
Gatekeeper resource as the manager couldn't set the onwer references
to other objects.
Closes #88

Enable manager role to modify operator finalizers

---

config/rbac/base/auth_proxy_client_clusterrole.yaml

It's using v1beta1 which has been deprecated for a while now. Let's use
v1 instead.

use v1 for the metrics-reader ClusterRole object

---

Makefile
README.md
bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
config/gatekeeper/v1_namespace_gatekeeper-system.yaml
config/manager/manager.yaml
config/rbac/overlays/openshift/kustomization.yaml
controllers/gatekeeper_controller.go
main.go
pkg/bindata/bindata.go
pkg/util/namespace.go
pkg/util/platform.go

This adds the ability to use a default canonical namespace to install Gatekeeper when running on OpenShift, or default to using the same namespace as the operator on vanilla Kubernetes. As a result, the `WATCH_NAMESPACE` feature has been completely removed as this cluster scoped operator does not currently have a need for it.
Closes #93

Fix installing Gatekeeper when operator is deployed via OLM

---

Makefile
api/v1alpha1/gatekeeper_types.go
bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml
config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml

resolves https://github.com/gatekeeper/gatekeeper-operator/issues/103
We will need to use v1beta1 in order to publish gatekeeper operator in ocp 4.5 catalog. 
Once ocp 4.8 is released, we can upgrade to v1 as 4.5 will end of life.

Downgrade CRD to v1beta1

---

.github/workflows/release.yml
Makefile
deploy/gatekeeper-operator.yaml

This also updates the image tag in the release manifest from `latest` to use the specific release version image tag.

Verify release manifest in release workflow

---

.github/workflows/olm.yml

When invoking make bundle, the operator version passed in needs to match
the version in the CSV bundle. Therefore, it's best not to rely on a
hard-coded version as it will need to be updated each time a new release
of the operator is made because the CSV version will have been updated.
Instead of hard-coding the version, this change will use the version
that is stored in the Makefile, which is the canonical source for the
operator version and so will be kept updated for every release.

Use operator version from Makefile

---

.github/workflows/go.yml
.github/workflows/image.yml
.github/workflows/olm.yml
.github/workflows/release.yml
Makefile

GitHub Actions workflows should fetch all tags and branches so that the `git describe` that's used to generate the operator version that's logged at startup accurately reflects the tag/branch it's based off.

Fetch all tags and branches in GitHub Actions workflows

---

.github/workflows/release.yml
Makefile

The version tags created in this repo for official releases are annotated tags. However, this change is necessary to enable matching lightweight (non-annotated) tags because the GitHub Actions checkout@v2 action (step run just prior) will overwrite the annotated tag with a non-annotated one here https://github.com/actions/checkout/blob/5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f/src/git-source-provider.ts#L136-L141 as a result of the refspec created at https://github.com/actions/checkout/blob/5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f/src/ref-helper.ts#L94-L97. This issue is tracked at https://github.com/actions/checkout/issues/290. Once the issue is resolved, this step can be removed.

Enable matching lightweight non-annotated tags

---

.github/workflows/go.yml
.github/workflows/image.yml
.github/workflows/olm.yml
docs/releasing.md
scripts/kind-with-registry.sh

This also reverts commit bcd40c0 that ignored docs related changes from running CI due to https://github.com/gatekeeper/gatekeeper-operator/issues/123.

Add instructions doc for releasing gatekeeper operator

---

.github/workflows/go.yml
Makefile
api/v1alpha1/gatekeeper_types.go
api/v1alpha1/zz_generated.deepcopy.go
bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
bundle/manifests/operator.gatekeeper.sh_gatekeepers.yaml
config/crd/bases/operator.gatekeeper.sh_gatekeepers.yaml
config/gatekeeper/admissionregistration.k8s.io_v1beta1_mutatingwebhookconfiguration_gatekeeper-mutating-webhook-configuration.yaml
config/gatekeeper/apiextensions.k8s.io_v1beta1_customresourcedefinition_assign.mutations.gatekeeper.sh.yaml
config/gatekeeper/apiextensions.k8s.io_v1beta1_customresourcedefinition_assignmetadata.mutations.gatekeeper.sh.yaml
config/gatekeeper/apps_v1_deployment_gatekeeper-audit.yaml
config/gatekeeper/apps_v1_deployment_gatekeeper-controller-manager.yaml
config/gatekeeper/rbac.authorization.k8s.io_v1_clusterrole_gatekeeper-manager-role.yaml
config/rbac/base/role.yaml
config/samples/gatekeeper_with_all_values.yaml
controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go
pkg/bindata/bindata.go
test/gatekeeper_controller_test.go

This upgrades the Gatekeeper version to v3.3.0 and adds support for enabling Gatekeeper mutation.
This does not include the support for being able to set the `failurePolicy` or `namespaceSelector` fields in the `MutatingWebhookConfiguration` as is done in the `ValidatingWebhookConfiguration`. I plan to do this in a follow-up PR assuming it's also desired.
Also, I would like to add the Gatekeeper mutating bats e2e tests in a follow-up PR.
@mmirecki @fedepaol

Add support for Gatekeeper mutation

---

bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
config/samples/operator_v1alpha1_gatekeeper.yaml
controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go
controllers/merge/merge.go
controllers/merge/merge_test.go
pkg/util/constants.go
test/gatekeeper_controller_test.go

- Upon updating the `MutatingWebhookConfiguration` as a result of a Gatekeeper CR reconcile, this adds retention for the `caBundle` that was in generated and injected by Gatekeeper at startup. It also adds unit tests to exercise this logic.
- Fixes namespace overrides for the mutating webhook service to support any custom namespace and adds unit tests for it.
- Update the operator sample CR and bundle (alm-examples annotation) to use Gatekeeper `v3.3.0`.
@mmirecki @fedepaol

Retain MutationgWebhookConfiguration CABundle

---

config/samples/gatekeeper_with_all_values.yaml
test/gatekeeper_controller_test.go
test/util/util.go

- Increases timeout for deletion of the Gatekeeper CR in-between tests.
- Refactors mutation enabled, `failurePolicy` and `namespaceSelector` e2e tests.

Add namespaceSelector e2e tests

---

controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go
test/e2e/e2e.go
test/e2e/gatekeeper_controller.go

This adds support for deleting Gatekeeper mutating and validating resources when mutation and validation are disabled respectively. That is, when mutation or validation are enabled and then subsequently disabled, this now deletes the resources previously installed by those config options being enabled. This also adds unit tests and e2e tests to verify the expected behavior.
Fixes #131 
@fedepaol @mmirecki

Delete Gatekeeper mutating/validating resources when mutation/validation is disabled

---

config/samples/affinity_pod.yaml
config/samples/gatekeeper_with_all_values.yaml
controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go
controllers/merge/merge.go
pkg/util/constants.go
test/e2e/e2e.go
test/e2e/gatekeeper_controller.go

Deploying webhooks with a non Ignore failure policy can negatively affect the stability of the cluster if the deployment backing it fails. This PR causes the webhooks to be created with an Ignore failure policy, and changes it to the desired value once the gatekeeper controller deployment is fully operational

Temporarily deploy webhooks with failurePolicy set to Ignore

---

.github/workflows/go.yml
.github/workflows/image.yml
.github/workflows/olm.yml
.github/workflows/release.yml
Makefile
scripts/kind-with-registry.sh
test/bats/test.bats
test/e2e/gatekeeper_controller.go

- Fix OPM build error. This was caused by using the -b option to create and checkout a new branch. Removing the -b option instead checks out the v1.15.1 tag in detached HEAD state.
- Increase long timeout to 5 minutes
- Update GitHub Actions hosted runner OS to latest ubuntu-20.04
- Fix culr image in bats test
- Output kind version in CI for debug purposes

Fix CI errors

---

Makefile

The namespace of the catalogsource was being kustomized while the sourceNamespace
in the subscription remain the same. The catalogsource couldn't be found when deploying.

Fix bug in kustomizing the namespace when deploying with OLM

---

bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
config/rbac/base/role.yaml
config/rbac/overlays/openshift/kustomization.yaml
controllers/gatekeeper_controller.go
pkg/util/constants.go

- Add RBAC permission to operator to CRUD namespaces
- Remove RBAC patch operation in OpenShift overlay
- make manifests
- Do not skip creating the Namespace asset
Closes #169

Do not skip creating the namespace asset in kubernetes

---

Makefile
test/e2e/e2e.go
test/e2e/gatekeeper_controller.go
test/e2e/options.go

- Remove need for pointer dereference
- Reduce check ready replicas timeout to default
- Add -delete-timeout flag for e2e tests
- Set e2e timeout flags for Makefile test-e2e target

Add -delete-timeout flag to e2e tests and override defaults in e2e CI tests

---

bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml

This update makes the operator's Deployment name unique from the
previous version of the operator so that we can update the labels for
the operator's Deployment. Updating the labels is essential so that we
can avoid duplicating labels with the Gatekeeper resources as Gatekeeper
is also using the default 'control-plane: controller-manager' label in
its Deployments, Service, Namespace, and PolicyDisruptionBudget
resources. Otherwise it inhibits filtering output based on this label if
the label is identical between both the operator and Gatekeeper.
The labels field is an immutable field, so the only way to update the
label is to create a new Deployment with a different name. This loses
some of the rolling upgrade features of Deployments, but OLM will
properly cleanup the old Deployment. …

Update operator Deployment name

---

bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
config/samples/gatekeeper_e2e_test.yaml
config/samples/operator_v1alpha1_gatekeeper.yaml
controllers/gatekeeper_controller.go
controllers/gatekeeper_controller_test.go
test/e2e/gatekeeper_controller.go

- Remove all fields from Gatekeeper sample CR
- Remove image field from Gatekeeper e2e test CR
- Override image with env var or use default
- Update unit tests for testing image overrides
- Update e2e tests to remove support for image field
- make bundle

Remove support for spec.image.image field in Gatekeeper CR

---

Makefile
bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
config/gatekeeper/apps_v1_deployment_gatekeeper-audit.yaml
config/gatekeeper/apps_v1_deployment_gatekeeper-controller-manager.yaml
config/manager/manager.yaml
config/samples/gatekeeper_with_all_values.yaml
pkg/bindata/bindata.go

- Set Gatekeeper version to v3.5.2
- Update deployed Gatekeeper image to v3.5.2
- Update sample configs to use Gatekeeper v3.5.2
- make import-manifests
- make update-bindata
- make bundle

Update Operator to support Gatekeeper v3.5.2

---

.github/workflows/image.yaml
.github/workflows/release.yaml

The docker-build make target has other dependencies that use Go. Since
the specific version of Go was not set up until later in the Github
Action, I think the version it was using was whatever happened to
already be on that ubuntu VM. That could cause problems, possibly
including the recent image build failures.
Signed-off-by: Justin Kulikauskas <jkulikau@redhat.com>

Move Go setup earlier in workflows

---

.github/workflows/image.yaml
.github/workflows/olm_tests.yaml
.github/workflows/release.yaml
Makefile

Remove reliance on variables in favor of explicit Makefile setting for which version the bundle replaces

correct PR merge actions

---

Makefile

- Use `gsed` if Mac is detected
- Consistently use `GOOS` and `GOARCH` for installing binaries
- Use binaries installed in `LOCAL_BIN` -- don't rely on the local version
- Add `clean` Make target to remove stale binaries

Update Make commands for Mac

---

Makefile
bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
docs/releasing.md

This is a new channel so replaces don't apply. Instead, a skipRange should be used to indicate that you can update directly from all previous versions.

Set the correct replaces and skipRange

---

controllers/gatekeeper_controller.go

Previous versions of the Gatekeeper operator had a custom role definition for OpenShift but as part of the upgrade to v3.11, it was consolidated to a single role. It is benign to have an OpenShift specific permission on other clusters since that API group does not exist on other clusters. This keeps maintenance simpler.
Relates:
https://issues.redhat.com/browse/ACM-5295

Fix the missing role file when deploying on OCP

---

deploy/gatekeeper-operator.yaml

Relates:
https://issues.redhat.com/browse/ACM-5295

Remove unnecessary permission in the deploy file

---

bundle/manifests/gatekeeper-operator.clusterserviceversion.yaml
config/default/manager_auth_proxy_patch.yaml
config/manager/manager.yaml
deploy/gatekeeper-operator.yaml

This allows OpenShift to set the correct profile automatically for backwards compatibility with OCP 4.10.
Note in OpenShift 4.10, it sets the annotation `openshift.io/scc: restricted` on the pod when `seccompProfile` is unset. For OCP 4.13, it sets the annotation `openshift.io/scc: restricted-v2` on the pod when `seccompProfile` is unset.

Stop setting seccompProfile on the operator pods
